### ISSUE TITLE
New Token every time

### ISSUE THREAD

**Issue by kenny3794** [drotiro/boxfs2#11]
Everytime I run boxfs, I have to acquire a new token.  Not sure why the old token file isn't usable.  The token file is in the folder referenced by the config file and has 0400 permissions.

```
# Conf file for boxfs
# edit to fit your needs.

# Put oauth2 tokens here:
token_file = /media/Data/.box/token

# Set a valid mount point
mountpoint = /media/Data/Box.com

verbose    = no
largefiles = no

# Configure the cache
cache_dir   = /media/Data/.box/cache
expire_time = 1440

# Configure your uid and gid below:
#uid = 1000
#gid = 1000
fperm = 644
dperm = 755
```

Is this a bug?  Am I misinterpreting the performance?

**Comment by nogweii** [comment]
I think this is happening again -- now box uses `api.box.com`.

**Comment by parnmatt** [comment]
Indeed, I have to re-authenticate each time,

**Comment by michaelansel** [comment]
I did some asking around, and nothing should have changed with the API. Maybe double check that the refresh token is getting updated after every use? (Refresh tokens are single use)
