### ISSUE TITLE
Auth code not working

### ISSUE THREAD

**Issue by rkwiles** [drotiro/boxfs2#12]
I can not get Auth to work.
Command line is sudo ./boxfs -f /home/casucan/.boxfs/conf
## Conf file looks like.
# Conf file for boxfs
# edit to fit your needs.
# Put oauth2 tokens here:

token_file = /home/casucan/.boxfs/token
# Set a valid mount point

mountpoint = /usr/local/boxfs

verbose    = no
largefiles = no
# Configure the cache

cache_dir   = /home/casucan/.boxfs/cache
expire_time = 1440
# Configure your uid and gid below:
# uid = 1000
# gid = 1000

fperm = 644
## dperm = 755

It asks me to go to the  https://www.box.com/api/oauth2/authorize web site to get the code.
I type in code and get error message.
Unable to get access token: Auth code doesn't exist or is invalid for the client

How can I correct this?

**Comment by drotiro** [comment]
Hi,
two things:
- it is not required to run boxfs as root (I advice you to run as a regular user instead)
- the code is valid only for 30 seconds, so you have to copy and paste it from the browser quickly

Please delete your token file and try again.
If you still have problems please enable verbose logging and look at your syslog.

Regards.
