### ISSUE TITLE
fstab mount?

### ISSUE THREAD

**Issue by lockheed** [drotiro/boxfs2#14]
HI,

Thank you for this project. Is there a way to add boxfs mount to fstab?

**Comment by drotiro** [comment]
Hi.
here you can find some proposed solution the problem: http://stackoverflow.com/questions/1554178/how-to-register-fuse-filesystem-type-with-mount8-and-fstab
I haven't tried them anyway.
Another option is an init script that runs boxfs with the correct user (it shouldn't run as root)

Regards,
Domenico

**Comment by stephensrmmartin** [comment]
The solution to the problem that you linked in your response requires the -o option, with long options.
E.g.,
You have to be able to run: boxfs /path/to/mountpoint -o conffile=~/.boxfs/conf
Currently, you cannot do that.
mount -t fuse boxfs ~/Box -o conffile=~/.boxfs/conf
Should run:
boxfs ~/Box -o conffile=~/.boxfs/conf
and that command should work.
That is how mounting programs should work:
mountingProgram <origin, if applicable> <dest> -o <opt1, opt2>
