### ISSUE TITLE
Can cp to Box but get 0 byte file when cp from to local machine

### ISSUE THREAD

**Issue by brimur** [drotiro/boxfs2#18]
Hi, I know its been a few years since you worked on this but I was looking for an alternative to davfs2 that would allow direct access to files for streaming rather than caching first and I came across boxfs2. I got it setup and have my Box account mounted and I can copy files TO the box folder but when I try to access a file in the Box folder or cp it locally the command completes instantly and the file size is 0 bytes. There is no error. If you could help or have suggestions I would be grateful. Alternatively if boxfs2 is similar to davfs2 in that the full file has to be cached locally before accessing it is possible could you tell me? It would save me the time of troubleshooting the copy issue. Thanks

**Comment by drotiro** [comment]
Hi,
the file should be downloaded when you access it.
Please enable verbose logging and look in your syslog files.

Regards,
D.

**Comment by brimur** [comment]
Thank you for the response. After one or two reboots it seemed to work but unfortunately it caches the file locally (similar to davfs) before presenting it to the application that requested it so it will not stream media. It is not possible to disable cache in davfs, is it possible to disable cache in boxfs2? It would be great if the file stream could go directly to the application without caching first.

**Comment by drotiro** [comment]
Unfortunately, it's not possible to disable caching, sorry.
