### ISSUE TITLE
cannot paste authentication code after "code:"

### ISSUE THREAD

**Issue by katrienw** [drotiro/boxfs2#19]
I have tried many times but cannot paste after the instruction:  
"Visit https://app.box.com/api/oauth2/authorize?response_type=code&client_id=f9ss11y2w0hg5r04jsidxlhk4pil28cf to authorize, then paste the code below
Code:"

After the word "code:" pasting is not possible, then the 30 seconds time run out.
What can I do to get boxfs authenticated?

many thanks in advance

**Comment by drotiro** [comment]
Hi,
pasting should be enabled after the word code.
Have you tried pasting in the shell before starting boxfs? Does it work?

Please tell me what distro/version are you using.

Regards

**Comment by katrienw** [comment]
Thank you for your reply. Pasting works normally in the shell, it was only
in the "code:" prompt that pasting seemed not possible.

Finally I got it working when trying in shell on the raspberry itself.
Before I had been trying over ssh remote shell from my pc. Maybe that
caused the issue. Other problem might have been that on my pc browser I was
already logged in my box account, before starting the authentication.
Op di 19 jun. 2018 om 10:05 schreef Domenico Rotiroti <
notifications@github.com>

**Comment by drotiro** [comment]
I'm glad you got it working.
Being already logged should not be an issue.

D.
