### ISSUE TITLE
installer for boxfs

### ISSUE THREAD

**Issue by vbhupathi** [drotiro/boxfs2#21]
Is there a installer file for boxfs like .deb or something else which supports Linux Mint 19?

thanks,

**Comment by ritiek** [comment]
I don't think so there is. But, it was a breeze for me to compile it on Linux Mint 19.

**Comment by drotiro** [comment]
Sorry, I don't provide packages for the varous Linux distros, but you should be able to compile it yourself as explained in the readme.

Regards.
